title: Naga Santhosh Reddy Vootukuri
description: Principal Software Engineering Manager | Microsoft Azure SQL Engineering
baseurl: "/Resume"
url: "https://sunnynagavo.github.io"

# Build settings
markdown: kramdown
remote_theme: sproogen/modern-resume-theme@v2.0.10
sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme Config
layout: default
name: Naga Santhosh Reddy Vootukuri
email: sunnycoder5@gmail.com
phone: +1 (XXX) XXX-XXXX
website: https://dzone.com/authors/sunnynagavo
darkmode: false

# Social links
github_username: sunnynagavo
linkedin_username: naga-santhosh-reddy-vootukuri-5a67a133
additional_links:
  - title: DZone
    icon: fas fa-globe
    url: https://dzone.com/authors/sunnynagavo
  - title: Speaking
    icon: fas fa-microphone
    url: https://sessionize.com/naga-santhosh-reddy-vootukuri
  - title: Scholar
    icon: fas fa-graduation-cap
    url: https://scholar.google.com/citations?user=dlQOtWYAAAAJ&hl=en
  - title: Mentoring
    icon: fas fa-chalkboard-teacher
    url: https://adplist.org/mentors/sunny

# Content
content:
  - title: About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Accomplished Principal Software Engineering Manager with **17+ years** of progressive leadership experience at Microsoft, specializing in Azure SQL Database technologies, cloud computing, and artificial intelligence. Demonstrated expertise in leading cross-functional teams, driving product innovation, and delivering scalable solutions to **millions of users worldwide**. Distinguished thought leader with **7 published research papers**, **27 technical articles**, and recognition as a **top cloud computing expert**. Active mentor, conference speaker, and technical reviewer contributing to the advancement of software engineering practices and AI applications.

      Recently featured in [Business Insider](https://www.businessinsider.com/microsoft-manager-ai-reduces-busywork-not-daily-workload-2024-10) discussing AI's impact on engineering management and productivity.

# Footer
footer_show_references: false

# Google Analytics
google_analytics: UA-000000-0 